app:
  name: 'isling-be'
  version: '0.1.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'isling-be'

postgres:
  pool_max: 2
  url: 'postgres://user:pass@localhost:5432/postgres'

jwt:
  secret: 'secret'
  audience: 'isling.me'
  exp: 3600

gorse:
  url: 'http://127.0.0.1:8087'
