app:
  name: 'isling_be'
  env: 'production'
  version: '1.0.0'

http:
  port: '8080'
  rate_limit: 64
  rate_limit_user_activities_post: 4

logger:
  log_level: 'info'
  rollbar_env: 'isling_be'

postgres:
  pool_max: 2
  url: 'postgres://user:pass@localhost:5432/postgres'

jwt:
  secret: 'secret'
  audience: 'isling.me'
  exp: 3600

gorse:
  url: 'http://127.0.0.1:8087'

surreal:
  url: 'ws://localhost:8000/rpc'
  ns: 'iplay'
  db: 'iplay'
